export const dateFilterCopy = {
  selectDate: "选择日期",
  clear: "清除",
};

export const calculatorCopy = {
  title: "计算器",
  amountAriaLabel: "金额",
  openCalculator: "打开计算器",
  invalidValue: "请输入有效金额。",
  delete: "删除",
  calculate: "计算",
  confirm: "确认",
  clearAll: "AC",
  clearAllLabel: "全部清除",
  error: "无法计算",
  add: "加",
  subtract: "减",
  multiply: "乘",
  divide: "除",
};

export const calendarCopy = {
  today: "今天",
  yesterday: "昨天",
  clear: "清除",
  previousMonth: "上个月",
  nextMonth: "下个月",
  weekDaysMon: ["一", "二", "三", "四", "五", "六", "日"],
  currency: "货币",
  noData: "暂无数据",
  less: "少",
  more: "多",
  count: (v: { count: string | number }) => `${v.count}笔`,
  expense: "支出",
  noConsumption: "无消费",
  heatmapLevel0: "无消费",
  heatmapLevel1: "很少",
  heatmapLevel2: "较少",
  heatmapLevel3: "中等",
  heatmapLevel4: "较多",
  heatmapLevel5: "很多",
  dateFormat: (v: { year: string | number; month: string | number }) => `${v.year}年${v.month}月`,
  productName: "商品名称",
  addNote: "添加备注",
};

export const periodBarCopy = {
  label: "区间",
  choose: "选择区间",
  previous: "上一期",
  next: "下一期",
  week: "周",
  month: "月",
  year: "年",
  all: "全部",
  custom: "自定义",
  apply: "应用",
  from: "开始日期",
  to: "结束日期",
  customTooLong: ({ days }: { days: number }) => `自定义区间最长 ${days} 天，请缩短后再应用。`,
  previousYear: "上一年",
  nextYear: "下一年",
  yearName: ({ year }: { year: number }) => `${year}年`,
  monthName: ({ month }: { month: number }) => `${month}月`,
};
