import type { CommonLucideIcon } from "@/config/icons";

export const settingsCopy = {
  theme: "主题",
  themeAuto: "跟随系统",
  themeLight: "浅色模式",
  themeDark: "深色模式",
  aiLanguage: "AI 输出语言",
  timeZone: "时区",
  timeZoneDesc: "决定「今天」和每月从哪天算起，所有分账共用。",
  mainCurrency: "主货币",
  collapseEntries: "默认折叠账单",
  preferredCurrencies: "偏好货币",
  preferredCurrenciesNone: "未选择币种",
  preferredCurrenciesSummary: (v: { currencies: string | number; count: string | number }) =>
    `${v.currencies}（${v.count} 种）`,
  preferredCurrenciesSearch: "搜索币种",
  preferredCurrenciesNoResults: "没有匹配的币种",
  currencyRetired: (v: { currency: string }) => `${v.currency}（不再支持新选）`,
  manageCategories: "管理分类",
  categoryAssignmentActive: "分类任务进行中，结束后才能修改分类。",
  moveCategoryUp: "上移",
  moveCategoryDown: "下移",
  editCategory: (v: { name: string | number }) => `编辑分类 ${v.name}`,
  categoryMoreActions: (v: { name: string | number }) => `${v.name}的更多操作`,
  editCategoryDialog: "编辑分类",
  deleteCategoryDialog: "删除分类",
  deleteCategoryDescription: (v: { name: string | number }) =>
    `确定删除分类「${v.name}」吗？相关明细将变为未分类。`,
  categoryName: "分类名称",
  categoryNameTaken: "已有同名分类。",
  aiPrompt: "账本提示词",
  learnPreferences: "从我的修改中学习",
  learnedPreferences: "自动学到的偏好",
  learnedPreferencesEmpty: "还没有学到偏好。修改几条 AI 的结果后，第二天会出现在这里。",
  learnedPreferencesUpdatedAt: (v: { date: string }) => `最近整理于 ${v.date}`,
  clearLearnedPreferences: "清空",
  clearLearnedPreferencesTitle: "清空学到的偏好？",
  clearLearnedPreferencesDescription: "偏好文字和已记录的修改都会删除，之后从头开始学习。",
  clearLearnedPreferencesSuccess: "已清空学到的偏好",
  clearLearnedPreferencesFailed: "清空失败，请稍后重试",
  newCategoryPlaceholder: "新分类名称",
  addCategory: "添加",
  updateSuccess: "设置更新成功",
  updateFailed: "更新失败，请稍后重试",
  unsupportedCurrency: "所选币种暂不受汇率数据支持",
  validationFailed: "设置内容无效，请检查后重试",
  saving: "（保存中…）",
  mainCurrencyMustBeEnabled: "主货币必须包含在偏好货币中。",
  categoriesSaved: "分类已保存",
  saveCategoriesFailed: "未保存任何分类更改，请修正后重试。",
  discardCategoryChangesTitle: "放弃分类更改？",
  discardCategoryChangesDescription: "未保存的分类修改会丢失。",
  discardCategoryEditTitle: "放弃分类编辑？",
  discardCategoryEditDescription: "此分类编辑器中的更改将丢失。",
  credentialCreated: "API 密钥已创建",
  credentialDeleted: "API 密钥已删除",
  createFailed: "创建失败",
  deleteFailed: "删除失败",
  categoryDescription: "分类描述",
  generatingMetadata: "正在生成描述和图标…",
  retryMetadata: "重试生成",
  categoryItemCount: (v: { count: string | number }) => `${v.count} 条明细`,
  uncategorized: "未分类",
  signOut: "退出登录",
  signedInAs: "当前登录",
  signOutHere: "在这台设备上退出",
  signOutConfirmTitle: "退出登录？",
  signOutConfirmDescription: "退出前会清除本机缓存的账本数据。",
  selectIcon: "选择图标",
  selectedIcon: (v: { name: string | number }) => `已选择图标：${v.name}`,
  icons: "图标",
  iconNames: {
    Utensils: "餐饮",
    Coffee: "咖啡",
    Wine: "酒水",
    ShoppingBag: "购物袋",
    ShoppingCart: "购物车",
    Shirt: "服装",
    Gamepad2: "游戏",
    Music: "音乐",
    Ticket: "门票",
    Film: "电影",
    Bus: "公交",
    Car: "汽车",
    TrainFront: "火车",
    Plane: "飞机",
    Bike: "自行车",
    Stethoscope: "医疗",
    Heart: "健康",
    House: "住房",
    Building: "建筑",
    Key: "钥匙",
    Book: "书籍",
    GraduationCap: "教育",
    Laptop: "电脑",
    Phone: "手机",
    Camera: "相机",
    Headphones: "耳机",
    Wifi: "网络",
    Wallet: "钱包",
    CreditCard: "信用卡",
    Banknote: "现金",
    Receipt: "小票",
    PiggyBank: "储蓄",
    Briefcase: "工作",
    Hammer: "维修",
    Dumbbell: "健身",
    Baby: "婴幼儿",
    Dog: "宠物",
    Gift: "礼物",
    Glasses: "眼镜",
    Umbrella: "雨具",
    Watch: "手表",
    Hotel: "酒店",
    MapPin: "地点",
    Luggage: "行李",
    Crown: "皇冠",
    Star: "星标",
    Lightbulb: "创意",
    Palette: "艺术",
    Scissors: "理发",
    Tag: "标签",
    Truck: "配送",
    Zap: "水电",
    Package: "其他",
  } satisfies Record<CommonLucideIcon, string>,
  credentialBookChanged: "已更新 API 密钥的分账",
  credentialBookChangeFailed: "修改 API 密钥的分账失败",
  categoriesChangedElsewhere: "分类已在别处更改，这些修改无法保存。",
  reloadCategories: "载入最新分类",
};

export const settingsBooksCopy = {
  name: "名称",
  namePlaceholder: "分账名称",
  add: "新增分账",
  addTitle: "新增分账",
  addDesc: "起个简短的名字，之后可改名或归档。",
  rename: (v: { name: string | number }) => `重命名 ${v.name}`,
  moveUpShort: "上移",
  moveDownShort: "下移",
  moreActions: (v: { name: string | number }) => `${v.name}的更多操作`,
  archive: "归档",
  archiveTitle: (v: { name: string | number }) => `归档「${v.name}」？`,
  archiveDesc: "归档后不再出现在切换器中，账单仍计入总账，可随时恢复。",
  archived: "分账已归档",
  restore: "恢复",
  restored: "分账已恢复",
  archivedBadge: "已归档",
  archivedSection: "已归档的分账",
  delete: "删除",
  deleteTitle: (v: { name: string | number }) => `删除「${v.name}」？`,
  deleteDesc: "删除后无法恢复，仅限没有账单和 API 密钥的分账。",
  deleted: "分账已删除",
  hasRecords: "该分账还有账单，不能删除。请改为归档。",
  hasCredentials: "还有 API 密钥绑定到该分账，请先改绑这些密钥。",
  invalidName: "分账名称需要 1–20 个字符。",
  notFound: "找不到该分账，可能已被删除。",
  lastBook: "最后一个分账不能归档或删除。",
  nameTaken: "已有同名分账。",
  saveFailed: "保存分账失败。",
  empty: "还没有分账。",
};

export const serviceCredentialsCopy = {
  newCredential: "新建 API 密钥",
  noCredentials: "暂无 API 密钥",
  createdAt: (v: { date: string | number }) => `创建于 ${v.date}`,
  createTitle: "新建 API 密钥",
  createDesc: "创建 API 密钥，供外部系统访问此账本。",
  namePlaceholder: "密钥名称（例如：自动记账脚本）",
  createSuccessTitle: "API 密钥已创建",
  createSuccessDesc: "完整密钥只显示这一次，请立即复制保存。",
  copyCredential: "复制密钥",
  saved: "我已保存",
  deleteTitle: "删除 API 密钥",
  deleteDesc: (v: { name: string | number }) =>
    `删除「${v.name}」后，使用它的应用将无法访问，无法撤销。`,
  deleteButton: (v: { name: string | number }) => `删除${v.name}`,
  maxActive: "每个账本最多可有 20 个有效的 API 密钥。",
  bookUnavailable: "所选分账已归档或删除，请换一个。",
  copied: "API 密钥已复制到剪贴板",
  bookDesc: "通过此密钥上传的账单会归入该分账。",
  changeBook: (v: { name: string | number }) => `修改「${v.name}」的分账`,
  archivedBook: "（已归档）",
};
